opt: opt_enc.c keygen.c
		 gcc -g -o opt_enc opt_enc.c
		 gcc -g -o opt_enc_d opt_enc_d.c
		 gcc -g -o keygen keygen.c
		 gcc -g -o opt_dec opt_dec.c
		 gcc -g -o opt_dec_d opt_dec_d.c
clean: 
			rm -f keygen opt_enc opt_enc_d opt_dec opt_dec_d
